pipeline {
    agent any

    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
              stage ('checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/shaikshoaib27/gcpdevops.git'
            }
        }
		stage('Set creds') {
            steps {
              
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./google-compute-engine/jenkins.json'
		            sh 'pwd'
		    sh 'cd google-compute-engine'
                       
               
            }
        }
	
	stage('Auth-Project') {
	 steps {
		 dir('google-compute-engine')
		 {
        sh 'ls -ltr'
        sh 'pwd'
        sh 'gcloud auth activate-service-account jenkins@mi-uat-lab.iam.gserviceaccount.com --key-file=jenkins.json'
    }
    }
	} 
	stage('Create Instance') {
	 steps {
    
    sh 'gcloud compute instances create pipeline-vm --zone=us-central1-a --machine-type-n1-standard-1 --tags=http-server --create-disk=auto-delete=yes,boot=yes,device-name=instance1,image=projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20221018,mode=rw,size=10,type=projects/mi-uat-lab/zones/us-central1-a/diskTypes/pd-balanced --metadata=startup-script=startup-script.sh'
		 
    }
    }
}
}
