pipeline {
    agent any

    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
              stage ('checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/shaikshoaib27/gcpdevops.git'
            }
        }
		stage('Set creds') {
            steps {
              
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./google-compute-engine/jenkins.json'
		            sh 'pwd'
		    sh 'cd google-compute-engine'
                       
               
            }
        }
	
	stage('Auth-Project') {
	 steps {
		 dir('google-compute-engine')
		 {
        sh 'ls -ltr'
        sh 'pwd'
        sh 'gcloud auth activate-service-account jenkins@mi-uat-lab.iam.gserviceaccount.com --key-file=jenkins.json'
    }
    }
	} 
	stage('Create Instance') {
	 steps {
    
    sh 'gcloud compute instances create pipeline-vm --zone=europe-west2-a --tags=http-server --metadata=startup-script.sh'
        
    }
    }
}
}
